### ISSUE TITLE
netifaces not listed in setup.py requirements

### ISSUE THREAD

**Issue by rambo** [andreikop/python-ws-discovery#11]
And thus importing WSDiscovery fails unless netifaces is separately installed.

> (onvif_py3) rambombp2015:onvif rambo$ pip install https://github.com/andreikop/python-ws-discovery/archive/master.zip
> Collecting https://github.com/andreikop/python-ws-discovery/archive/master.zip
>   Downloading https://github.com/andreikop/python-ws-discovery/archive/master.zip
> Installing collected packages: WSDiscovery
>   Running setup.py install for WSDiscovery ... done
> Successfully installed WSDiscovery-0.2
> (onvif_py3) rambombp2015:onvif rambo$ python onvif_discovery_test.py 
> Traceback (most recent call last):
>   File "onvif_discovery_test.py", line 1, in <module>
>     from WSDiscovery import WSDiscovery
>   File "/Users/rambo/.virtualenvs/onvif_py3/lib/python3.6/site-packages/WSDiscovery.py", line 15, in <module>
>     import netifaces
> ModuleNotFoundError: No module named 'netifaces'
> (onvif_py3) rambombp2015:onvif rambo$ pip install netifaces
> Collecting netifaces
>   Using cached netifaces-0.10.5.tar.gz
> Building wheels for collected packages: netifaces
>   Running setup.py bdist_wheel for netifaces ... done
>   Stored in directory: /Users/rambo/Library/Caches/pip/wheels/9f/40/bd/1f8e0f83e36399900d81bebfd7ece579931ced3a5d9383284b
> Successfully built netifaces
> Installing collected packages: netifaces
> Successfully installed netifaces-0.10.5
> (onvif_py3) rambombp2015:onvif rambo$ python onvif_discovery_test.py 
> urn:uuid:00071858-1858-6a40-5840-e06290e2667e:http://172.17.24.39/onvif/device_service
> <WSDiscovery.Service object at 0x10be37fd0>
> ['http://172.17.24.39/onvif/device_service']
> (onvif_py3) rambombp2015:onvif rambo$ 
>

**Comment by petri** [comment]
Sadly, this package is still using distutils, which does not support specifying requirements. See #2 for background...
