### ISSUE TITLE
Fix package metadata

### ISSUE THREAD

**Issue by petri** [andreikop/python-ws-discovery#13]
The setup.py has the following info:

      author='L.A. Fernando',
      author_email='lafernando@gmail.com',
      url='https://github.com/hlamer/python-ws-discovery.git'

Is this correct? Who's this L.A. Fernando? Is the source of python-ws-discovery code originally from somewhere else?

This should be checked and if needed, fixed prior to publishing at PyPI.

**Comment by petri** [comment]
Ok, kick me for not remembering the history is right there on the front page :D 

I guess the URL should be then changed to `https://github.com/andreikop/python-ws-discovery`.

**Comment by andreikop** [comment]
I've updated urls, emails and names to point at me as the author.
But if @lafernando or you would like to maintain the project, I'd be happy.
