### ISSUE TITLE
set up travis-ci

### ISSUE THREAD

**Issue by petri** [andreikop/python-ws-discovery#17]
Now that we've started adding tests, I'd suggest we set up CI for this package at https://travis-ci.org .

@andreikop can you create an account for yourself at travis & add python-ws-discovery there please? Or, if you add me as a repo owner here, I can do that. Either way.

**Comment by andreikop** [comment]
I've enabled this project on Travis.
https://travis-ci.org/andreikop/python-ws-discovery
Do I need to do some other actions?

**Comment by petri** [comment]
No, thanks.
