### ISSUE TITLE
probe.py getTypes missing

### ISSUE THREAD

**Issue by tosscaster** [andreikop/python-ws-discovery#18]
probe.py

from ..util import createSkelSoapMessage, getBodyEl, getHeaderEl, addElementWithText, \
                   addTypes, addScopes, getDocAsString, getScopes

getTypes is missing

**Comment by andreikop** [comment]
@petri , would you take a look?

**Comment by andreikop** [comment]
@petri, leave some comments when closing issue. Or mention it in a commit message.
It is not clear, if the issue is fixed, not reproduced or ignored.
