### ISSUE TITLE
Make TTL Configurable

### ISSUE THREAD

**Issue by hunterjm** [andreikop/python-ws-discovery#19]
Looking at the [SOAP over UDP specification](http://specs.xmlsoap.org/ws/2004/09/soap-over-udp/soap-over-udp.pdf) section 4.3, they recommend TTL be set to 1, which you are doing in this library.  However, it would be nice to have this value configurable.

My use case is trying to discover ONVIF cameras, which use WS-Discovery, that are on a separate VLAN.  The TTL value being set to 1 prevents the packet from making the hop over to the other VLAN.

What are your thoughts on bumping the TTL to 4 (the SSDP default), or at least making it configurable?

**Comment by andreikop** [comment]
Hi
I would agree with Soap over UDP specification. TTL 1 is expected behavior for the majority of cases. But it is good idea to make TTL configurable.
I don't actively support this project. Your PR is welcome.

**Comment by andreikop** [comment]
PR merged
