### ISSUE TITLE
publish in PyPI

### ISSUE THREAD

**Issue by petri** [andreikop/python-ws-discovery#2]
Probably good idea to switch to using setuptools prior to that... @hlamer, I am willing to contribute if you have time to accept pull requests? Or give me contrib rights?

**Comment by hlamer** [comment]
Is it necessary to switch to setuptools?
distutils is a standard module, so, available on any system.
Just open a PR.

**Comment by petri** [comment]
Well, setuptools is as far as I know pretty much de facto 'standard' in Python packaging, short of being actually included in stdlib. It's installed by default in virtualenvs, and I think even pip requires it. All the Python scaffolding tools use it. I think all the linux distros include it, too. So a system having setuptools installed is more a rule than an exception.

I will open a PR.

**Comment by hlamer** [comment]
Yes, but if does setuptools provide any advantages for **this** project?

**Comment by petri** [comment]
Setuptools is just better for packaging and using Python packages. That's it scope, so I am not sure what advantages you expect a better packaging library should have beyond that, to be sufficiently useful to use? Setuptools has [good documentation](https://setuptools.readthedocs.io/en/latest/) if you want details. 

For the simplest packages, I am sure there is no absoute need. But if this package is for example split into several modules and published in PyPI, setuptools larger feature set comes in handy. Which I hope to find some time to contribute to. 

But if you as package maintainer insist on not making a change that has no sufficient value to you, that's fine. I'll then just fork away as I have no interest in packaging things with distutils any more nowadays.

**Comment by hlamer** [comment]
@petri, I know that setuptools is generally better. I'm just don't see any advantages for this very small and simple project. And I see a disadvantage - setuptools might be missing on some systems.
Now setup.py is very simple and it would not be better with setuptools. When we face the first problem which is easier solvable with setuptools I don't mind migrating.

**Comment by petri** [comment]
@andreikop, please see #11. Would you accept a PR that switches to setuptools? How about adding a requirements.txt file as well, for pip users?

**Comment by andreikop** [comment]
Hi
I will

**Comment by petri** [comment]
Submitted a PR. Shall we make a PyPI release so we can close this issue after that? @andreikop can you first check whether setup.py is correct, as per #13?

Can you make the PyPI release? Or if you like, I can make the PyPI release and transfer the ownership to you.

**Comment by andreikop** [comment]
@petri, I'm not going to actively develop/maintain the project, but I don't mind if you've done a PyPI release and transferred the ownership or own it.

**Comment by petri** [comment]
@andreikop ok. I will make a PyPI release then, and add you as admin or owner. Can you give me commit rights to this repository? I'd like to be able to add release notes or changelog, etc.

**Comment by andreikop** [comment]
@petri, you should have commit rights now!

**Comment by petri** [comment]
Thanks @andreikop. Package released. Let me know your pypi user name and I'll add you to package owners. I'll close this issue after that.

**Comment by andreikop** [comment]
I've registered on PyPi as andreikop

**Comment by petri** [comment]
Added andreikop as package owner.
