### ISSUE TITLE
Should only create socket on "UP" interfaces

### ISSUE THREAD

**Issue by hongquan** [andreikop/python-ws-discovery#23]
`WsDiscovery.searchServices` stops working when there are these interfaces in the system:

- `wg0`, created by WireGuard.
- `docker0`, created by Docker.

**Comment by hongquan** [comment]
Update: When `docker0` appears in the system, if we exclude its address (`172.17.0.1`), `WSDiscovery` cannot search services (return empty list).

**Comment by andreikop** [comment]
Hi
Thank you for the report.
I don't maintain this project actively now, but PRs are welcome.

**Comment by hongquan** [comment]
@andreikop 

Is your goal to support both Linux and Mac OSX? I plan to use [pyroute2](https://pypi.org/project/pyroute2/) to filter network interfaces which is multicast-capable. But it is Linux only.

**Comment by andreikop** [comment]
What happens if you try to use non multicast-capable intereface?
Is it possible to try to send message from interface and continue to work in case of exception?

`pyroute2` is fine, but resolving the issue wo external dependencies would be even better

**Comment by hongquan** [comment]
> What happens if you try to use non multicast-capable intereface?

I want to filter out WireGuard's interface. There is no way to recognize it, other than a hint that this interface doesn't have MULTICAST flag, as shown below:

```sh
$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 94:c6:91:a9:0b:6f brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.30/24 brd 192.168.0.255 scope global dynamic enp3s0
       valid_lft 79864sec preferred_lft 79864sec
    inet6 fe80::96c6:91ff:fea9:b6f/64 scope link 
       valid_lft forever preferred_lft forever
3: wlp2s0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 18:56:80:ac:84:56 brd ff:ff:ff:ff:ff:ff
5: wg0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none 
    inet 192.168.18.3/24 scope global wg0
       valid_lft forever preferred_lft forever
```

**Comment by andreikop** [comment]
It seems like keeping current behavior is more preferable for the majority of users, than adding dependencies and loosing MacOSX compatibility.
But you can create a fork for your task.

**Comment by hongquan** [comment]
Thanks, @andreikop
