### ISSUE TITLE
Generic program name "discover"

### ISSUE THREAD

**Issue by helmutg** [andreikop/python-ws-discovery#26]
The package creates a command simply named `discover`. Such a generic name is likely to cause conflict with other packages when added to a Linux distribution such as Debian. I suggest renaming the command to something less generic to avoid any such conflict from arising. For instance, using `wsdiscover` as a command name would avoid such problems at little loss in usability. Would you agree to rename the tool?

I note that currently, there is no such conflict in Debian on this particular name, but it is easier to rename things before they gain widespread use.

**Comment by andreikop** [comment]
Thank you, @helmutg 
I've renamed the script
