### ISSUE TITLE
Python3 only?

### ISSUE THREAD

**Issue by petri** [andreikop/python-ws-discovery#31]
Python2 is approaching end of life. How should WS-Discovery package approach that? Some options:
- drop Python2 support in the next version?
- introduce a new major version that's Python3 only?
- continue supporting both?

Thoughts? I am thinking of doing more refactoring to make it easier to support asyncio, and adding some docs. Improving the package would of course overall be easier if we were able to drop Python2 support. So I'd prefer dropping it.

How about cutting a release from current master & making that the last release to support Python2?

**Comment by andreikop** [comment]
Are there any strong reasons to drop Python2 support?
There are people who has to support legacy systems on Py2. I wouldn't like to make their job even harder.

**Comment by petri** [comment]
I think Python2 being practically at end of life now is reason enough. People who need to support Python2 can stick to 1.1.2 - or 1.1.3 as soon as that is released. Having FUTURE releases be Python3 only is not making anybody's job harder. Quite to the contrary, forcing Python2 support requirements on anyone contributing to WSDiscovery is making it harder to contribute for no good reason at this time in Python2 lifecycle. 

For example, I am working on some considerable improvements and frankly, I have no interest whatsoever limiting the code to Python2 compliance. Of course I could always release that as WSDiscoveryNG or whatever, but I'd rather not.

We could even have two branches, one for Python2 support & one without. Say, a 1.x.x branch that keeps Python2 compat and a 2.x.x that's Python3 only.

**Comment by andreikop** [comment]
If Py2 compatibility slows down somebody - let's drop it.
Just document in README.md that versions up to x.x.x are Py2 compatible and next are not

**Comment by petri** [comment]
Python3 - only PR #33 submitted.

**Comment by andreikop** [comment]
Now Py3 only
