### ISSUE TITLE
Versions > 2.0

### ISSUE THREAD

**Issue by petri** [andreikop/python-ws-discovery#32]
I've got a new Python3-only development version at:

https://github.com/koodaamo/python-ws-discovery

See the updated changes doc there, plus the actual package docs. 

The simple probing test passes, and I was able to discover my IP cam as usual, so the discovery part is mostly working already. I have not yet tested the service publishing part though; something is likely missing there.

**Comment by andreikop** [comment]
Cool.
Open PRs when ready.

**Comment by petri** [comment]
Created a 2.x branch here with my latest changes.

**Comment by petri** [comment]
PR #33 submitted now.
