### ISSUE TITLE
Enable github pages / readthedocs documentation

### ISSUE THREAD

**Issue by petri** [andreikop/python-ws-discovery#34]
@andreikop you need to enable this; I don't have permissions. This is needed so that the package docs will show up here, once #33 is merged.

Go to settings tab for the repo, and enable github pages. Make sure to select the option that uses docs from master branch's /doc directory.

**Comment by andreikop** [comment]
@petri, thank you for the cool PR.
I've enabled the docs. 
Currently see "site not found". Probably github needs some time to deploy the pages

**Comment by andreikop** [comment]
btw, it is also possible to have the docs built and updated automatically on

**Comment by petri** [comment]
> btw, it is also possible to have the docs built and updated automatically on https://readthedocs.org/

That'd be fine as well. We'd need some webhooks that are set up in the settings as well.

**Comment by petri** [comment]
Yeah lets' use RTD instead. I just realized small part of documentation is a little out of date because I did not rebuild the docs.

**Comment by andreikop** [comment]
I'll add project to readthedocs  when having time

**Comment by petri** [comment]
We'll probably need to restructure the docs a bit to make the Sphinx build pipeline compatible with RTD. Let me know if you need me to help out. I actually tried RTD earlier but cannot remember off my head what it was that it needed...

**Comment by andreikop** [comment]
I've added a badge to the README which points to https://readthedocs.org/projects/python-ws-discovery/

@petri, could you please check which web hooks are necessary to rebuild the docs on commit to the repository? There should be some urls and secrets on the readthedocs project admin page.

**Comment by petri** [comment]
The rtd build passes now. @andreikop I added you as a maintainer for the project. See "integrations" -> there's a github webhook there that I've set up. The rtd docs seem to indicate that this is enough and the rest can be set on the github side. Relevant doc here: https://docs.readthedocs.io/en/stable/webhooks.html#github

**Comment by andreikop** [comment]
Docs are built automatically now.
I've fixed the link in README
