### ISSUE TITLE
Unclosed sockets on exit

### ISSUE THREAD

**Issue by SamuelYvon** [andreikop/python-ws-discovery#54]
This library has not been updated in a bit; I'm not sure I'll get an answer. In the threaded discovery service, a selector is opened and sockets are shoved in as needed. However, those sockets are never closed when stopping the service

**Comment by andreikop** [comment]
@SamuelYvon I don't support the library actively now, but do merge PRs

**Comment by SamuelYvon** [comment]
I have a fork I can adapt for this which closes all the sockets. I'll contribute later if I have time

**Comment by SamuelYvon** [comment]
@andreikop See https://github.com/andreikop/python-ws-discovery/pull/55

**Comment by andreikop** [comment]
Merged #55
Thanks!
