### ISSUE TITLE
没有 IPv6 Scope ID 会导致异常

### ISSUE THREAD

**Issue by chenmohan123** [andreikop/python-ws-discovery#61]
![屏幕截图 2024-05-30 142102](https://github.com/andreikop/python-ws-discovery/assets/5992155/fd12d7c5-0b10-4b18-981b-547669fb258d)

**Comment by chenmohan123** [comment]
![Uploading 屏幕截图 2024-05-30 143132.png…]()

**Comment by chenmohan123** [comment]
![屏幕截图 2024-05-30 143132](https://github.com/andreikop/python-ws-discovery/assets/5992155/4aadbd22-93d3-4175-9125-7e03f6572361)

**Comment by felmoreno1726** [comment]
I'm looking at the same issue. It was introduced with IPv6 support in the last pull request. @Breina 

https://github.com/andreikop/python-ws-discovery/pull/59

**Comment by felmoreno1726** [comment]
Where you able to resolve this @chenmohan123 ? I think we could make IPv6 optional, and/or clean this up.

**Comment by felmoreno1726** [comment]
I have a similar error. With this stack trace.

```
    wsd.start()
venv/lib64/python3.12/site-packages/wsdiscovery/threaded.py:404: in start
    self._startThreads()
venv/lib64/python3.12/site-packages/wsdiscovery/threaded.py:380: in _startThreads
    self._addrsMonitorThread_v6 = AddressMonitorThread(self, socket.AF_INET6)
venv/lib64/python3.12/site-packages/wsdiscovery/threaded.py:52: in __init__
    self._updateAddrs()
venv/lib64/python3.12/site-packages/wsdiscovery/threaded.py:64: in _updateAddrs
    self._wsd._networkAddressAdded(addr)
venv/lib64/python3.12/site-packages/wsdiscovery/discovery.py:101: in _networkAddressAdded
    self.addSourceAddr(addr)
venv/lib64/python3.12/site-packages/wsdiscovery/threaded.py:417: in addSourceAddr
    self._networkingThread_v6.addSourceAddr(addr)
venv/lib64/python3.12/site-packages/wsdiscovery/threaded.py:141: in addSourceAddr
    self._multiInSocket.setsockopt(self._get_ip_proto(), self._get_ip_join(), self._makeMreq(addr))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <NetworkingThreadIPv6(Thread-2, started daemon 140235888126496)>
addr = IPv6Address('fe80::42:6bff:fea0:1b11%docker0')

    def _makeMreq(self, addr):
>       return struct.pack("=16si", socket.inet_pton(socket.AF_INET6, MULTICAST_IPV6_ADDRESS), int(addr.scope_id))
E       ValueError: invalid literal for int() with base 10: 'docker0'
```

**Comment by Breina** [comment]
I'm guessing a library updated its signature. Both ipv4 and ipv6 were working when this got merged.

Will check this after work.

**Comment by felmoreno1726** [comment]
It might be. It might also be that we are working with Virtual Network or Docker networks or that the discover routine is finding Services withing those, which were not accounted for in the code.

**Comment by wpyoga** [comment]
On Linux, the scope_id is a string. It's the same with a physical interface, so this is not specific to a virtual network (VPN) and Docker networks.
