### ISSUE TITLE
Licensing info in source file

### ISSUE THREAD

**Issue by Climax777** [andreikop/python-ws-discovery#8]
I think it would be prudent to add the license info in the source code.

**Comment by hlamer** [comment]
Hmm. I don't really know if it is necessary.
I don't mind a PR if you are sure that headers are correct.

**Comment by petri** [comment]
@Climax777 By "license info" do you mean adding a copy of the verbatim license? Or something different? I believe including a license copy has been mandatory in the past; but I don't know if that's still so, either.

**Comment by petri** [comment]
@Climax777 we have copy of license in the pkg and it is also mentioned in pkg metadata. I think that should be enough. If there’s something else you had in mind, please reopen and clarify.
